language: objective-c
matrix:
  include:
  - osx_image: xcode9.3
    env: XCODE_VER=93
  - osx_image: xcode9.2
    env: XCODE_VER=92
  - osx_image: xcode9
    env: XCODE_VER=90
branches:
  only:
  - master
env:
  global:
  - tag=v0.0.6
  - secure: l44iaTHdL4J4ePXWNA1Ja9RuWqNvgZdM7ymA5JYbEpXUwZcl6DKGH5N8ropmwnxzmSLp+1t5us1S6NJRJBCBU8xd59/Y7ohKYoleOcYk5Fl4rPoilyw4TM8j00PdPBriqWZ5+QBeNxUpohWXbKSfHCYYJPiyBD16+M+8zCAxkzvT3HXe/f5pJ4/XuedUqUx02tERPs7L71Q5sbvpa9K3koRL4fPM5QKvSNyww0ayxZt5kQTHe+ULt8LNsEn6MN60kUdcTahJZT/NZEh4wyniJblSllz5TXAKL47dnAtSni2cODlWRJLvjFZyCa1Olq6UpHegC8RqlAJyR4znzMGiG07/fQuonVoYi1pBW3BCfcx5tBH9TSpF8MUz97S66Ef7r7cc4aojmov1LLQ5p1/R0oP4yHuSMjCjLirc36QQS0ADVXITpkqG3NM4bnwtY5QEW/GagSG2ZrV6917HHUlsUT7JdFL3J2Ct8YVEikjrXo/2s30mvprJ0vOgBUqoL07lcVamjGRpqigyS39hsqFfv9MTeNkEGVc/3BBR6Iou2xJNgUGRheuPKIhdAKtwGOruV1i5as3+hD/Afq5uwHYRmqgc8piOOgX0UzHDMSNW6/m24NbYTY6rdD2UKRhLixefow1ItsHKdIDiVLXtOyWSThsaika+fOuzohZK5YQ72jQ=
before_script:
- brew tap tcnksm/ghr
- brew install ghr
script:
- make release
after_script:
- ghr -t $TOKEN -u shreyaganguly1 -r travisRelease -c master -b "Releasing $tag" $tag releases/
