language: objective-c
osx_image: xcode9.3

branches:
  only:
    - master
env:
  - UNIVERSAL_OUTPUTFOLDER = $TRAVIS_BUILD_DIR/universal BUILD_DIR = $TRAVIS_BUILD_DIR/Payabbhi-distributable
script:
  - mkdir -p $(UNIVERSAL_OUTPUTFOLDER)
  -	xcodebuild -target "travisiOSsample" -configuration Release ONLY_ACTIVE_ARCH=NO -sdk iphoneos  BUILD_DIR=$(BUILD_DIR) clean build
  -	xcodebuild -target "travisiOSsample" -configuration Release -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO BUILD_DIR=$(BUILD_DIR) clean build
  -	cp -R $(BUILD_DIR)/Release-iphoneos/travisiOSsample.framework $(UNIVERSAL_OUTPUTFOLDER)/
  -	cp -R $(BUILD_DIR)/Release-iphonesimulator/travisiOSsample.framework/Modules/travisiOSsample.swiftmodule/. $(UNIVERSAL_OUTPUTFOLDER)/travisiOSsample.framework/Modules/travisiOSsample.swiftmodule
  -	lipo -create -output $(UNIVERSAL_OUTPUTFOLDER)/travisiOSsample.framework/travisiOSsample $(BUILD_DIR)/Release-iphonesimulator/travisiOSsample.framework/travisiOSsample $(BUILD_DIR)/Release-iphoneos/travisiOSsample.framework/travisiOSsample
  -	mv $(UNIVERSAL_OUTPUTFOLDER)/travisiOSsample.framework $(TRAVIS_BUILD_DIR)
  -	tar -cvzf travisiOSsample-iOS.tar.gz travisiOSsample.framework
  -	rm -rf $(TRAVIS_BUILD_DIR)/travisiOSsample.framework
